# Generated by Django 2.0.6 on 2018-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbmoduleversion',
            name='cause',
        ),
        migrations.AlterField(
            model_name='tbrecord',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
