# Generated by Django 2.0.6 on 2018-07-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huanjin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_jc', models.CharField(max_length=20, verbose_name='环境简称')),
                ('h_name', models.CharField(max_length=40, verbose_name='环境名称')),
                ('tag_bj', models.CharField(max_length=40, verbose_name='tag标记')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbmoduleversion',
            name='cause',
        ),
        migrations.AlterField(
            model_name='tbrecord',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
